apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: pod-info
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '4.0.1'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: pod-info
      interval: 1m