apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lamia
  namespace: flux-system
spec:
  image: ghcr.io/mrwormhole/lamia
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lamia
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lamia
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: lamia
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  sourceRef:
    kind: GitRepository
    name: flux-system    
  interval: 10m
  update:
    path: "./clusters/falk-debby/lamia"
    strategy: Setters
