apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lamia
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mrwormhole/lamia
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lamia
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: lamia
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: lamia
  namespace: flux-system
spec:
  image: ghcr.io/mrwormhole/lamia
  interval: 5m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lamia
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lamia
  policy:
    semver:
      range: 0.x.x
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: lamia
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: lamia
  update:
    path: "./manifests"
    strategy: Setters
