apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lamia
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/mrwormhole/lamia
  ref:
    branch: master
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: lamia
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests"
  prune: true
  timeout: 1m
  sourceRef:
    kind: GitRepository
    name: lamia