apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 96h
  chart:
    spec:
      chart: rook-ceph
      version: "1.13.1"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 24h
  values:
    image:
      repository: rook/ceph
      tag: v1.13.1
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    csi:
      enableRbdDriver: true
      enableCephfsDriver: true
      enableCSIHostNetwork: true
      enableCephfsSnapshotter: true
      enableNFSSnapshotter: true
      enableRBDSnapshotter: true
      enablePluginSelinuxHostMount: false
      enableCSIEncryption: false
      provisionerReplicas: 2

      serviceMonitor:
        # -- Enable ServiceMonitor for Ceph CSI drivers
        enabled: false
        # -- Service monitor scrape interval
        interval: 5s
        # -- ServiceMonitor additional labels
        labels: {}
        # -- Use a different namespace for the ServiceMonitor
        namespace:

      cephcsi:
        # @default -- `quay.io/cephcsi/cephcsi:v3.10.1`
        image:

      registrar:
        # @default -- `registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.1`
        image:

      provisioner:
        # @default -- `registry.k8s.io/sig-storage/csi-provisioner:v3.6.2`
        image:

      snapshotter:
        # @default -- `registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2`
        image:

      attacher:
        # @default -- `registry.k8s.io/sig-storage/csi-attacher:v4.4.2`
        image:

      resizer:
        # @default -- `registry.k8s.io/sig-storage/csi-resizer:v1.9.2`
        image:

      csiAddons:
        enabled: false

      nfs:
        # disabled because NFS is experimental
        # https://rook.io/docs/rook/v1.12/Storage-Configuration/Ceph-CSI/ceph-csi-drivers/
        enabled: false

      topology:
        enabled: false

      cephFSAttachRequired: true
      rbdAttachRequired: true
      nfsAttachRequired: true

    scaleDownOperator: true
    hostpathRequiresPrivileged: false
    enableOBCWatchOperatorNamespace: true

    monitoring:
      enabled: false
