apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  interval: 96h
  chart:
    spec:
      chart: rook-ceph
      version: "v1.13.2"
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      interval: 24h
  values:
    image:
      repository: rook/ceph
      tag: v1.13.2
      pullPolicy: IfNotPresent

    scaleDownOperator: true
    monitoring:
      enabled: false
    crds:
      enabled: true
