apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-system
spec:
  interval: 24h
  chart:
    spec:
      chart: minio
      version: "5.0.x"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
      interval: 5m
  values:
    ignoreChartChecksums: true # if you don't have flux, set this to false
    existingSecret: "minio-credentials"
    drivesPerNode: 1
    replicas: 3
    pools: 1

    users:
      - accessKey: OsynT1d6hYh0uqZN
        existingSecret: minio-credentials
        existingSecretKey: secretKey
        policy: consoleAdmin

    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 10Gi

    resources:
      requests:
        memory: 500Mi
        cpu: 250m
      limits:
        memory: 500Mi
        cpu: 250m

    buckets:
      - name: logs
        policy: none